# Generated by Django 4.2.1 on 2023-06-05 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2023, 6, 5), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
