# Generated by Django 4.2.1 on 2023-06-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0009_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
